###
#
# Browse Books
#
GET http://localhost:4004/catalog/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-language=de

###
#
# Get Author wit ID 101
#
GET http://localhost:4004/catalog/Authors(101)

###
#
# Update Author with ID 101
#
POST http://localhost:4004/catalog/Authors
Content-Type: application/json

{"ID": 010, "name": "Some Author"}


###
#
# Order a Book
#
POST http://localhost:4004/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{
  "book_ID" : "1001", 
  "qty": 100
}


